{% set name = "typed-settings" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typed-settings-{{ version }}.tar.gz
  sha256: 73e88e6f517cfbd22845bc293137720df38f5b6644a38c430256f32c0c6049f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - attrs >=20.3
    - cattrs >=1.7
    - python >=3.7
    - toml >=0.10

test:
  imports:
    - typed_settings
    - typed_settings.attrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/sscherfke/typed-settings
  summary: Typed settings based on attrs classes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
