{% set name = "typed-settings" %}
{% set version = "24.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typed_settings-{{ version }}.tar.gz
  sha256: 96e51f56c37ab8d6199177dc0147393fa63e598a5f01d53a0f4d6481030d9e2c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py < 37]

requirements:
  host:
    - hatchling
    - pip
    - python
  run:
    - python
    - attrs >=22.1
    - cattrs >=22.2
    - tomli >=2  # [py < 311]

test:
  imports:
    - typed_settings
    - typed_settings.attrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/sscherfke/typed-settings
  summary: Typed settings based on attrs classes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdsmith
    - asford
