{% set name = "typed-settings" %}
{% set version = "23.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typed_settings-{{ version }}.tar.gz
  sha256: d1eb16899d1d567209f930d20fed3eceaeb723525c287de255edf8a454505fd5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py < 37]

requirements:
  host:
    - hatchling
    - pip
    - python
  run:
    - python
    - attrs >=22.1
    - cattrs >=22.2
    - tomli >=2  # [py < 311]

test:
  imports:
    - typed_settings
    - typed_settings.attrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/sscherfke/typed-settings
  summary: Typed settings based on attrs classes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdsmith
    - asford
